name: marketing-micro-fe-deployment

on:
  push:
    branches:
      - master
    paths:
      - 'packages/marketing/**'
      # - '.github/workflows/**'

defaults:
  run:
    working-directory: packages/marketing

env:
    AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
    AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
    AWS_DEFAULT_REGION: ap-south-1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run build

      - run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/marketing/latest
      - run: aws cloudfront create-invalidation --distribution-id E3RREJ68XBBZ2Y --paths "/marketing/latest/remoteEntry.js"
        